name: Build and Push PHP Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-php-image:
    uses: agon-mustafa/shared-workflows/.github/workflows/build-push-docker-hub-template.yaml@main
    with:
      working_directory: ./php
      image_repository: agonmustafa/docker-labs
      image_tag: php-example
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PAT: ${{ secrets.DOCKER_HUB_PAT }}
      SHARED_WORKFLOWS_PAT: ${{ secrets.SHARED_WORKFLOWS_PAT }}  # Add this line to access the shared workflows
