name: Build and Push PHP Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-php-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx build \
            --file ./Dockerfile \
            --tag ${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            --load \
            .
        env:
          IMAGE_REPOSITORY: agonmustafa/docker-labs
          IMAGE_TAG: php-example

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PAT }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }}
