name: Validate Build

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    uses: agon-mustafa/shared-workflows/.github/workflows/validate-build-template.yaml@main
    with:
      working_directory: ./php
      image_repository: agonmustafa/docker-labs
      image_tag: php-example
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PAT: ${{ secrets.DOCKER_HUB_PAT }}
      SHARED_WORKFLOWS_PAT: ${{ secrets.SHARED_WORKFLOWS_PAT }}  # Add this line to access the shared workflows
